var flash;
(function (flash) {
    var __native;
    (function (__native) {
        var format;
        (function (format) {
            var swf;
            (function (swf) {
                var factories;
                (function (factories) {
                    factories.ActionUnknown = flash.__native.format.swf.data.actions.ActionUnknown;
                    factories.IAction = flash.__native.format.swf.data.actions.IAction;
                    factories.ActionGetURL = flash.__native.format.swf.data.actions.swf3.ActionGetURL;
                    factories.ActionGotoFrame = flash.__native.format.swf.data.actions.swf3.ActionGotoFrame;
                    factories.ActionGotoLabel = flash.__native.format.swf.data.actions.swf3.ActionGotoLabel;
                    factories.ActionNextFrame = flash.__native.format.swf.data.actions.swf3.ActionNextFrame;
                    factories.ActionPlay = flash.__native.format.swf.data.actions.swf3.ActionPlay;
                    factories.ActionPreviousFrame = flash.__native.format.swf.data.actions.swf3.ActionPreviousFrame;
                    factories.ActionSetTarget = flash.__native.format.swf.data.actions.swf3.ActionSetTarget;
                    factories.ActionStop = flash.__native.format.swf.data.actions.swf3.ActionStop;
                    factories.ActionStopSounds = flash.__native.format.swf.data.actions.swf3.ActionStopSounds;
                    factories.ActionToggleQuality = flash.__native.format.swf.data.actions.swf3.ActionToggleQuality;
                    factories.ActionWaitForFrame = flash.__native.format.swf.data.actions.swf3.ActionWaitForFrame;
                    factories.ActionAdd = flash.__native.format.swf.data.actions.swf4.ActionAdd;
                    factories.ActionAnd = flash.__native.format.swf.data.actions.swf4.ActionAnd;
                    factories.ActionAsciiToChar = flash.__native.format.swf.data.actions.swf4.ActionAsciiToChar;
                    factories.ActionCall = flash.__native.format.swf.data.actions.swf4.ActionCall;
                    factories.ActionCharToAscii = flash.__native.format.swf.data.actions.swf4.ActionCharToAscii;
                    factories.ActionCloneSprite = flash.__native.format.swf.data.actions.swf4.ActionCloneSprite;
                    factories.ActionDivide = flash.__native.format.swf.data.actions.swf4.ActionDivide;
                    factories.ActionEndDrag = flash.__native.format.swf.data.actions.swf4.ActionEndDrag;
                    factories.ActionEquals = flash.__native.format.swf.data.actions.swf4.ActionEquals;
                    factories.ActionGetProperty = flash.__native.format.swf.data.actions.swf4.ActionGetProperty;
                    factories.ActionGetTime = flash.__native.format.swf.data.actions.swf4.ActionGetTime;
                    factories.ActionGetURL2 = flash.__native.format.swf.data.actions.swf4.ActionGetURL2;
                    factories.ActionGetVariable = flash.__native.format.swf.data.actions.swf4.ActionGetVariable;
                    factories.ActionGotoFrame2 = flash.__native.format.swf.data.actions.swf4.ActionGotoFrame2;
                    factories.ActionIf = flash.__native.format.swf.data.actions.swf4.ActionIf;
                    factories.ActionJump = flash.__native.format.swf.data.actions.swf4.ActionJump;
                    factories.ActionLess = flash.__native.format.swf.data.actions.swf4.ActionLess;
                    factories.ActionMBAsciiToChar = flash.__native.format.swf.data.actions.swf4.ActionMBAsciiToChar;
                    factories.ActionMBCharToAscii = flash.__native.format.swf.data.actions.swf4.ActionMBCharToAscii;
                    factories.ActionMBStringExtract = flash.__native.format.swf.data.actions.swf4.ActionMBStringExtract;
                    factories.ActionMBStringLength = flash.__native.format.swf.data.actions.swf4.ActionMBStringLength;
                    factories.ActionMultiply = flash.__native.format.swf.data.actions.swf4.ActionMultiply;
                    factories.ActionNot = flash.__native.format.swf.data.actions.swf4.ActionNot;
                    factories.ActionOr = flash.__native.format.swf.data.actions.swf4.ActionOr;
                    factories.ActionPop = flash.__native.format.swf.data.actions.swf4.ActionPop;
                    factories.ActionPush = flash.__native.format.swf.data.actions.swf4.ActionPush;
                    factories.ActionRandomNumber = flash.__native.format.swf.data.actions.swf4.ActionRandomNumber;
                    factories.ActionRemoveSprite = flash.__native.format.swf.data.actions.swf4.ActionRemoveSprite;
                    factories.ActionSetProperty = flash.__native.format.swf.data.actions.swf4.ActionSetProperty;
                    factories.ActionSetTarget2 = flash.__native.format.swf.data.actions.swf4.ActionSetTarget2;
                    factories.ActionSetVariable = flash.__native.format.swf.data.actions.swf4.ActionSetVariable;
                    factories.ActionStartDrag = flash.__native.format.swf.data.actions.swf4.ActionStartDrag;
                    factories.ActionStringAdd = flash.__native.format.swf.data.actions.swf4.ActionStringAdd;
                    factories.ActionStringEquals = flash.__native.format.swf.data.actions.swf4.ActionStringEquals;
                    factories.ActionStringExtract = flash.__native.format.swf.data.actions.swf4.ActionStringExtract;
                    factories.ActionStringLength = flash.__native.format.swf.data.actions.swf4.ActionStringLength;
                    factories.ActionStringLess = flash.__native.format.swf.data.actions.swf4.ActionStringLess;
                    factories.ActionSubtract = flash.__native.format.swf.data.actions.swf4.ActionSubtract;
                    factories.ActionToInteger = flash.__native.format.swf.data.actions.swf4.ActionToInteger;
                    factories.ActionTrace = flash.__native.format.swf.data.actions.swf4.ActionTrace;
                    factories.ActionWaitForFrame2 = flash.__native.format.swf.data.actions.swf4.ActionWaitForFrame2;
                    factories.ActionAdd2 = flash.__native.format.swf.data.actions.swf5.ActionAdd2;
                    factories.ActionBitAnd = flash.__native.format.swf.data.actions.swf5.ActionBitAnd;
                    factories.ActionBitLShift = flash.__native.format.swf.data.actions.swf5.ActionBitLShift;
                    factories.ActionBitOr = flash.__native.format.swf.data.actions.swf5.ActionBitOr;
                    factories.ActionBitRShift = flash.__native.format.swf.data.actions.swf5.ActionBitRShift;
                    factories.ActionBitURShift = flash.__native.format.swf.data.actions.swf5.ActionBitURShift;
                    factories.ActionBitXor = flash.__native.format.swf.data.actions.swf5.ActionBitXor;
                    factories.ActionCallFunction = flash.__native.format.swf.data.actions.swf5.ActionCallFunction;
                    factories.ActionCallMethod = flash.__native.format.swf.data.actions.swf5.ActionCallMethod;
                    factories.ActionConstantPool = flash.__native.format.swf.data.actions.swf5.ActionConstantPool;
                    factories.ActionDecrement = flash.__native.format.swf.data.actions.swf5.ActionDecrement;
                    factories.ActionDefineFunction = flash.__native.format.swf.data.actions.swf5.ActionDefineFunction;
                    factories.ActionDefineLocal = flash.__native.format.swf.data.actions.swf5.ActionDefineLocal;
                    factories.ActionDefineLocal2 = flash.__native.format.swf.data.actions.swf5.ActionDefineLocal2;
                    factories.ActionDelete = flash.__native.format.swf.data.actions.swf5.ActionDelete;
                    factories.ActionDelete2 = flash.__native.format.swf.data.actions.swf5.ActionDelete2;
                    factories.ActionEnumerate = flash.__native.format.swf.data.actions.swf5.ActionEnumerate;
                    factories.ActionEquals2 = flash.__native.format.swf.data.actions.swf5.ActionEquals2;
                    factories.ActionGetMember = flash.__native.format.swf.data.actions.swf5.ActionGetMember;
                    factories.ActionIncrement = flash.__native.format.swf.data.actions.swf5.ActionIncrement;
                    factories.ActionInitArray = flash.__native.format.swf.data.actions.swf5.ActionInitArray;
                    factories.ActionInitObject = flash.__native.format.swf.data.actions.swf5.ActionInitObject;
                    factories.ActionLess2 = flash.__native.format.swf.data.actions.swf5.ActionLess2;
                    factories.ActionModulo = flash.__native.format.swf.data.actions.swf5.ActionModulo;
                    factories.ActionNewMethod = flash.__native.format.swf.data.actions.swf5.ActionNewMethod;
                    factories.ActionNewObject = flash.__native.format.swf.data.actions.swf5.ActionNewObject;
                    factories.ActionPushDuplicate = flash.__native.format.swf.data.actions.swf5.ActionPushDuplicate;
                    factories.ActionReturn = flash.__native.format.swf.data.actions.swf5.ActionReturn;
                    factories.ActionSetMember = flash.__native.format.swf.data.actions.swf5.ActionSetMember;
                    factories.ActionStackSwap = flash.__native.format.swf.data.actions.swf5.ActionStackSwap;
                    factories.ActionStoreRegister = flash.__native.format.swf.data.actions.swf5.ActionStoreRegister;
                    factories.ActionTargetPath = flash.__native.format.swf.data.actions.swf5.ActionTargetPath;
                    factories.ActionToNumber = flash.__native.format.swf.data.actions.swf5.ActionToNumber;
                    factories.ActionToString = flash.__native.format.swf.data.actions.swf5.ActionToString;
                    factories.ActionTypeOf = flash.__native.format.swf.data.actions.swf5.ActionTypeOf;
                    factories.ActionWith = flash.__native.format.swf.data.actions.swf5.ActionWith;
                    factories.ActionEnumerate2 = flash.__native.format.swf.data.actions.swf6.ActionEnumerate2;
                    factories.ActionGreater = flash.__native.format.swf.data.actions.swf6.ActionGreater;
                    factories.ActionInstanceOf = flash.__native.format.swf.data.actions.swf6.ActionInstanceOf;
                    factories.ActionStrictEquals = flash.__native.format.swf.data.actions.swf6.ActionStrictEquals;
                    factories.ActionStringGreater = flash.__native.format.swf.data.actions.swf6.ActionStringGreater;
                    factories.ActionCastOp = flash.__native.format.swf.data.actions.swf7.ActionCastOp;
                    factories.ActionDefineFunction2 = flash.__native.format.swf.data.actions.swf7.ActionDefineFunction2;
                    factories.ActionExtends = flash.__native.format.swf.data.actions.swf7.ActionExtends;
                    factories.ActionImplementsOp = flash.__native.format.swf.data.actions.swf7.ActionImplementsOp;
                    factories.ActionThrow = flash.__native.format.swf.data.actions.swf7.ActionThrow;
                    factories.ActionTry = flash.__native.format.swf.data.actions.swf7.ActionTry;
                    var SWFActionFactory = (function () {
                        function SWFActionFactory() {
                        }
                        SWFActionFactory.create = function (code, length, pos) {
                            code = ((code) >>> 0);
                            length = ((length) >>> 0);
                            pos = ((pos) >>> 0);
                            switch (code) {
                                case factories.ActionNextFrame.CODE: return new factories.ActionNextFrame(code, length, pos);
                                case factories.ActionPreviousFrame.CODE: return new factories.ActionPreviousFrame(code, length, pos);
                                case factories.ActionPlay.CODE: return new factories.ActionPlay(code, length, pos);
                                case factories.ActionStop.CODE: return new factories.ActionStop(code, length, pos);
                                case factories.ActionToggleQuality.CODE: return new factories.ActionToggleQuality(code, length, pos);
                                case factories.ActionStopSounds.CODE: return new factories.ActionStopSounds(code, length, pos);
                                case factories.ActionAdd.CODE: return new factories.ActionAdd(code, length, pos);
                                case factories.ActionSubtract.CODE: return new factories.ActionSubtract(code, length, pos);
                                case factories.ActionMultiply.CODE: return new factories.ActionMultiply(code, length, pos);
                                case factories.ActionDivide.CODE: return new factories.ActionDivide(code, length, pos);
                                case factories.ActionEquals.CODE: return new factories.ActionEquals(code, length, pos);
                                case factories.ActionLess.CODE: return new factories.ActionLess(code, length, pos);
                                case factories.ActionAnd.CODE: return new factories.ActionAnd(code, length, pos);
                                case factories.ActionOr.CODE: return new factories.ActionOr(code, length, pos);
                                case factories.ActionNot.CODE: return new factories.ActionNot(code, length, pos);
                                case factories.ActionStringEquals.CODE: return new factories.ActionStringEquals(code, length, pos);
                                case factories.ActionStringLength.CODE: return new factories.ActionStringLength(code, length, pos);
                                case factories.ActionStringExtract.CODE: return new factories.ActionStringExtract(code, length, pos);
                                case factories.ActionPop.CODE: return new factories.ActionPop(code, length, pos);
                                case factories.ActionToInteger.CODE: return new factories.ActionToInteger(code, length, pos);
                                case factories.ActionGetVariable.CODE: return new factories.ActionGetVariable(code, length, pos);
                                case factories.ActionSetVariable.CODE: return new factories.ActionSetVariable(code, length, pos);
                                case factories.ActionSetTarget2.CODE: return new factories.ActionSetTarget2(code, length, pos);
                                case factories.ActionStringAdd.CODE: return new factories.ActionStringAdd(code, length, pos);
                                case factories.ActionGetProperty.CODE: return new factories.ActionGetProperty(code, length, pos);
                                case factories.ActionSetProperty.CODE: return new factories.ActionSetProperty(code, length, pos);
                                case factories.ActionCloneSprite.CODE: return new factories.ActionCloneSprite(code, length, pos);
                                case factories.ActionRemoveSprite.CODE: return new factories.ActionRemoveSprite(code, length, pos);
                                case factories.ActionTrace.CODE: return new factories.ActionTrace(code, length, pos);
                                case factories.ActionStartDrag.CODE: return new factories.ActionStartDrag(code, length, pos);
                                case factories.ActionEndDrag.CODE: return new factories.ActionEndDrag(code, length, pos);
                                case factories.ActionStringLess.CODE: return new factories.ActionStringLess(code, length, pos);
                                case factories.ActionThrow.CODE: return new factories.ActionThrow(code, length, pos);
                                case factories.ActionCastOp.CODE: return new factories.ActionCastOp(code, length, pos);
                                case factories.ActionImplementsOp.CODE: return new factories.ActionImplementsOp(code, length, pos);
                                case factories.ActionRandomNumber.CODE: return new factories.ActionRandomNumber(code, length, pos);
                                case factories.ActionMBStringLength.CODE: return new factories.ActionMBStringLength(code, length, pos);
                                case factories.ActionCharToAscii.CODE: return new factories.ActionCharToAscii(code, length, pos);
                                case factories.ActionAsciiToChar.CODE: return new factories.ActionAsciiToChar(code, length, pos);
                                case factories.ActionGetTime.CODE: return new factories.ActionGetTime(code, length, pos);
                                case factories.ActionMBStringExtract.CODE: return new factories.ActionMBStringExtract(code, length, pos);
                                case factories.ActionMBCharToAscii.CODE: return new factories.ActionMBCharToAscii(code, length, pos);
                                case factories.ActionMBAsciiToChar.CODE: return new factories.ActionMBAsciiToChar(code, length, pos);
                                case factories.ActionDelete.CODE: return new factories.ActionDelete(code, length, pos);
                                case factories.ActionDelete2.CODE: return new factories.ActionDelete2(code, length, pos);
                                case factories.ActionDefineLocal.CODE: return new factories.ActionDefineLocal(code, length, pos);
                                case factories.ActionCallFunction.CODE: return new factories.ActionCallFunction(code, length, pos);
                                case factories.ActionReturn.CODE: return new factories.ActionReturn(code, length, pos);
                                case factories.ActionModulo.CODE: return new factories.ActionModulo(code, length, pos);
                                case factories.ActionNewObject.CODE: return new factories.ActionNewObject(code, length, pos);
                                case factories.ActionDefineLocal2.CODE: return new factories.ActionDefineLocal2(code, length, pos);
                                case factories.ActionInitArray.CODE: return new factories.ActionInitArray(code, length, pos);
                                case factories.ActionInitObject.CODE: return new factories.ActionInitObject(code, length, pos);
                                case factories.ActionTypeOf.CODE: return new factories.ActionTypeOf(code, length, pos);
                                case factories.ActionTargetPath.CODE: return new factories.ActionTargetPath(code, length, pos);
                                case factories.ActionEnumerate.CODE: return new factories.ActionEnumerate(code, length, pos);
                                case factories.ActionAdd2.CODE: return new factories.ActionAdd2(code, length, pos);
                                case factories.ActionLess2.CODE: return new factories.ActionLess2(code, length, pos);
                                case factories.ActionEquals2.CODE: return new factories.ActionEquals2(code, length, pos);
                                case factories.ActionToNumber.CODE: return new factories.ActionToNumber(code, length, pos);
                                case factories.ActionToString.CODE: return new factories.ActionToString(code, length, pos);
                                case factories.ActionPushDuplicate.CODE: return new factories.ActionPushDuplicate(code, length, pos);
                                case factories.ActionStackSwap.CODE: return new factories.ActionStackSwap(code, length, pos);
                                case factories.ActionGetMember.CODE: return new factories.ActionGetMember(code, length, pos);
                                case factories.ActionSetMember.CODE: return new factories.ActionSetMember(code, length, pos);
                                case factories.ActionIncrement.CODE: return new factories.ActionIncrement(code, length, pos);
                                case factories.ActionDecrement.CODE: return new factories.ActionDecrement(code, length, pos);
                                case factories.ActionCallMethod.CODE: return new factories.ActionCallMethod(code, length, pos);
                                case factories.ActionNewMethod.CODE: return new factories.ActionNewMethod(code, length, pos);
                                case factories.ActionInstanceOf.CODE: return new factories.ActionInstanceOf(code, length, pos);
                                case factories.ActionEnumerate2.CODE: return new factories.ActionEnumerate2(code, length, pos);
                                case factories.ActionBitAnd.CODE: return new factories.ActionBitAnd(code, length, pos);
                                case factories.ActionBitOr.CODE: return new factories.ActionBitOr(code, length, pos);
                                case factories.ActionBitXor.CODE: return new factories.ActionBitXor(code, length, pos);
                                case factories.ActionBitLShift.CODE: return new factories.ActionBitLShift(code, length, pos);
                                case factories.ActionBitRShift.CODE: return new factories.ActionBitRShift(code, length, pos);
                                case factories.ActionBitURShift.CODE: return new factories.ActionBitURShift(code, length, pos);
                                case factories.ActionStrictEquals.CODE: return new factories.ActionStrictEquals(code, length, pos);
                                case factories.ActionGreater.CODE: return new factories.ActionGreater(code, length, pos);
                                case factories.ActionStringGreater.CODE: return new factories.ActionStringGreater(code, length, pos);
                                case factories.ActionExtends.CODE: return new factories.ActionExtends(code, length, pos);
                                case factories.ActionGotoFrame.CODE: return new factories.ActionGotoFrame(code, length, pos);
                                case factories.ActionGetURL.CODE: return new factories.ActionGetURL(code, length, pos);
                                case factories.ActionStoreRegister.CODE: return new factories.ActionStoreRegister(code, length, pos);
                                case factories.ActionConstantPool.CODE: return new factories.ActionConstantPool(code, length, pos);
                                case factories.ActionWaitForFrame.CODE: return new factories.ActionWaitForFrame(code, length, pos);
                                case factories.ActionSetTarget.CODE: return new factories.ActionSetTarget(code, length, pos);
                                case factories.ActionGotoLabel.CODE: return new factories.ActionGotoLabel(code, length, pos);
                                case factories.ActionWaitForFrame2.CODE: return new factories.ActionWaitForFrame2(code, length, pos);
                                case factories.ActionDefineFunction2.CODE: return new factories.ActionDefineFunction2(code, length, pos);
                                case factories.ActionTry.CODE: return new factories.ActionTry(code, length, pos);
                                case factories.ActionWith.CODE: return new factories.ActionWith(code, length, pos);
                                case factories.ActionPush.CODE: return new factories.ActionPush(code, length, pos);
                                case factories.ActionJump.CODE: return new factories.ActionJump(code, length, pos);
                                case factories.ActionGetURL2.CODE: return new factories.ActionGetURL2(code, length, pos);
                                case factories.ActionDefineFunction.CODE: return new factories.ActionDefineFunction(code, length, pos);
                                case factories.ActionIf.CODE: return new factories.ActionIf(code, length, pos);
                                case factories.ActionCall.CODE: return new factories.ActionCall(code, length, pos);
                                case factories.ActionGotoFrame2.CODE: return new factories.ActionGotoFrame2(code, length, pos);
                                default: return new factories.ActionUnknown(code, length, pos);
                            }
                        };
                        return SWFActionFactory;
                    }());
                    factories.SWFActionFactory = SWFActionFactory;
                })(factories = swf.factories || (swf.factories = {}));
            })(swf = format.swf || (format.swf = {}));
        })(format = __native.format || (__native.format = {}));
    })(__native = flash.__native || (flash.__native = {}));
})(flash || (flash = {}));
//# sourceMappingURL=SWFActionFactory.js.map