var flash;
(function (flash) {
    var __native;
    (function (__native) {
        var format;
        (function (format) {
            var swf;
            (function (swf) {
                var factories;
                (function (factories) {
                    factories.ITag = flash.__native.format.swf.tags.ITag;
                    factories.TagCSMTextSettings = flash.__native.format.swf.tags.TagCSMTextSettings;
                    factories.TagDebugID = flash.__native.format.swf.tags.TagDebugID;
                    factories.TagDefineBinaryData = flash.__native.format.swf.tags.TagDefineBinaryData;
                    factories.TagDefineBits = flash.__native.format.swf.tags.TagDefineBits;
                    factories.TagDefineBitsJPEG2 = flash.__native.format.swf.tags.TagDefineBitsJPEG2;
                    factories.TagDefineBitsJPEG3 = flash.__native.format.swf.tags.TagDefineBitsJPEG3;
                    factories.TagDefineBitsJPEG4 = flash.__native.format.swf.tags.TagDefineBitsJPEG4;
                    factories.TagDefineBitsLossless = flash.__native.format.swf.tags.TagDefineBitsLossless;
                    factories.TagDefineBitsLossless2 = flash.__native.format.swf.tags.TagDefineBitsLossless2;
                    factories.TagDefineButton = flash.__native.format.swf.tags.TagDefineButton;
                    factories.TagDefineButton2 = flash.__native.format.swf.tags.TagDefineButton2;
                    factories.TagDefineButtonCxform = flash.__native.format.swf.tags.TagDefineButtonCxform;
                    factories.TagDefineButtonSound = flash.__native.format.swf.tags.TagDefineButtonSound;
                    factories.TagDefineEditText = flash.__native.format.swf.tags.TagDefineEditText;
                    factories.TagDefineFont = flash.__native.format.swf.tags.TagDefineFont;
                    factories.TagDefineFont2 = flash.__native.format.swf.tags.TagDefineFont2;
                    factories.TagDefineFont3 = flash.__native.format.swf.tags.TagDefineFont3;
                    factories.TagDefineFont4 = flash.__native.format.swf.tags.TagDefineFont4;
                    factories.TagDefineFontAlignZones = flash.__native.format.swf.tags.TagDefineFontAlignZones;
                    factories.TagDefineFontInfo = flash.__native.format.swf.tags.TagDefineFontInfo;
                    factories.TagDefineFontInfo2 = flash.__native.format.swf.tags.TagDefineFontInfo2;
                    factories.TagDefineFontName = flash.__native.format.swf.tags.TagDefineFontName;
                    factories.TagDefineMorphShape = flash.__native.format.swf.tags.TagDefineMorphShape;
                    factories.TagDefineMorphShape2 = flash.__native.format.swf.tags.TagDefineMorphShape2;
                    factories.TagDefineScalingGrid = flash.__native.format.swf.tags.TagDefineScalingGrid;
                    factories.TagDefineSceneAndFrameLabelData = flash.__native.format.swf.tags.TagDefineSceneAndFrameLabelData;
                    factories.TagDefineShape = flash.__native.format.swf.tags.TagDefineShape;
                    factories.TagDefineShape2 = flash.__native.format.swf.tags.TagDefineShape2;
                    factories.TagDefineShape3 = flash.__native.format.swf.tags.TagDefineShape3;
                    factories.TagDefineShape4 = flash.__native.format.swf.tags.TagDefineShape4;
                    factories.TagDefineSound = flash.__native.format.swf.tags.TagDefineSound;
                    factories.TagDefineSprite = flash.__native.format.swf.tags.TagDefineSprite;
                    factories.TagDefineText = flash.__native.format.swf.tags.TagDefineText;
                    factories.TagDefineText2 = flash.__native.format.swf.tags.TagDefineText2;
                    factories.TagDefineVideoStream = flash.__native.format.swf.tags.TagDefineVideoStream;
                    factories.TagDoABC = flash.__native.format.swf.tags.TagDoABC;
                    factories.TagDoABCDeprecated = flash.__native.format.swf.tags.TagDoABCDeprecated;
                    factories.TagDoAction = flash.__native.format.swf.tags.TagDoAction;
                    factories.TagDoInitAction = flash.__native.format.swf.tags.TagDoInitAction;
                    factories.TagEnableDebugger = flash.__native.format.swf.tags.TagEnableDebugger;
                    factories.TagEnableDebugger2 = flash.__native.format.swf.tags.TagEnableDebugger2;
                    factories.TagEnableTelemetry = flash.__native.format.swf.tags.TagEnableTelemetry;
                    factories.TagEnd = flash.__native.format.swf.tags.TagEnd;
                    factories.TagExportAssets = flash.__native.format.swf.tags.TagExportAssets;
                    factories.TagFileAttributes = flash.__native.format.swf.tags.TagFileAttributes;
                    factories.TagFrameLabel = flash.__native.format.swf.tags.TagFrameLabel;
                    factories.TagImportAssets = flash.__native.format.swf.tags.TagImportAssets;
                    factories.TagImportAssets2 = flash.__native.format.swf.tags.TagImportAssets2;
                    factories.TagJPEGTables = flash.__native.format.swf.tags.TagJPEGTables;
                    factories.TagMetadata = flash.__native.format.swf.tags.TagMetadata;
                    factories.TagNameCharacter = flash.__native.format.swf.tags.TagNameCharacter;
                    factories.TagPlaceObject = flash.__native.format.swf.tags.TagPlaceObject;
                    factories.TagPlaceObject2 = flash.__native.format.swf.tags.TagPlaceObject2;
                    factories.TagPlaceObject3 = flash.__native.format.swf.tags.TagPlaceObject3;
                    factories.TagPlaceObject4 = flash.__native.format.swf.tags.TagPlaceObject4;
                    factories.TagProductInfo = flash.__native.format.swf.tags.TagProductInfo;
                    factories.TagProtect = flash.__native.format.swf.tags.TagProtect;
                    factories.TagRemoveObject = flash.__native.format.swf.tags.TagRemoveObject;
                    factories.TagRemoveObject2 = flash.__native.format.swf.tags.TagRemoveObject2;
                    factories.TagScriptLimits = flash.__native.format.swf.tags.TagScriptLimits;
                    factories.TagSetBackgroundColor = flash.__native.format.swf.tags.TagSetBackgroundColor;
                    factories.TagSetTabIndex = flash.__native.format.swf.tags.TagSetTabIndex;
                    factories.TagShowFrame = flash.__native.format.swf.tags.TagShowFrame;
                    factories.TagSoundStreamBlock = flash.__native.format.swf.tags.TagSoundStreamBlock;
                    factories.TagSoundStreamHead = flash.__native.format.swf.tags.TagSoundStreamHead;
                    factories.TagSoundStreamHead2 = flash.__native.format.swf.tags.TagSoundStreamHead2;
                    factories.TagStartSound = flash.__native.format.swf.tags.TagStartSound;
                    factories.TagStartSound2 = flash.__native.format.swf.tags.TagStartSound2;
                    factories.TagSymbolClass = flash.__native.format.swf.tags.TagSymbolClass;
                    factories.TagUnknown = flash.__native.format.swf.tags.TagUnknown;
                    factories.TagVideoFrame = flash.__native.format.swf.tags.TagVideoFrame;
                    factories.TagSWFEncryptActions = flash.__native.format.swf.tags.etc.TagSWFEncryptActions;
                    factories.TagSWFEncryptSignature = flash.__native.format.swf.tags.etc.TagSWFEncryptSignature;
                    var SWFTagFactory = (function () {
                        function SWFTagFactory() {
                            this.implements_flash___native_format_swf_factories_ISWFTagFactory = null;
                        }
                        SWFTagFactory.prototype.create = function (type) {
                            type = ((type) >>> 0);
                            var cl = SWFTagFactory.sTypeToClass[type];
                            if (cl) {
                                return new cl();
                            }
                            return new factories.TagUnknown(type);
                        };
                        SWFTagFactory.sTypeToClass = [];
                        SWFTagFactory.__block0 = function () {
                            function $() {
                                SWFTagFactory.sTypeToClass[factories.TagEnd.TYPE] = factories.TagEnd;
                                SWFTagFactory.sTypeToClass[factories.TagShowFrame.TYPE] = factories.TagShowFrame;
                                SWFTagFactory.sTypeToClass[factories.TagDefineShape.TYPE] = factories.TagDefineShape;
                                SWFTagFactory.sTypeToClass[factories.TagPlaceObject.TYPE] = factories.TagPlaceObject;
                                SWFTagFactory.sTypeToClass[factories.TagRemoveObject.TYPE] = factories.TagRemoveObject;
                                SWFTagFactory.sTypeToClass[factories.TagDefineBits.TYPE] = factories.TagDefineBits;
                                SWFTagFactory.sTypeToClass[factories.TagDefineButton.TYPE] = factories.TagDefineButton;
                                SWFTagFactory.sTypeToClass[factories.TagJPEGTables.TYPE] = factories.TagJPEGTables;
                                SWFTagFactory.sTypeToClass[factories.TagSetBackgroundColor.TYPE] = factories.TagSetBackgroundColor;
                                SWFTagFactory.sTypeToClass[factories.TagDefineFont.TYPE] = factories.TagDefineFont;
                                SWFTagFactory.sTypeToClass[factories.TagDefineText.TYPE] = factories.TagDefineText;
                                SWFTagFactory.sTypeToClass[factories.TagDoAction.TYPE] = factories.TagDoAction;
                                SWFTagFactory.sTypeToClass[factories.TagDefineFontInfo.TYPE] = factories.TagDefineFontInfo;
                                SWFTagFactory.sTypeToClass[factories.TagDefineSound.TYPE] = factories.TagDefineSound;
                                SWFTagFactory.sTypeToClass[factories.TagStartSound.TYPE] = factories.TagStartSound;
                                SWFTagFactory.sTypeToClass[factories.TagDefineButtonSound.TYPE] = factories.TagDefineButtonSound;
                                SWFTagFactory.sTypeToClass[factories.TagSoundStreamHead.TYPE] = factories.TagSoundStreamHead;
                                SWFTagFactory.sTypeToClass[factories.TagSoundStreamBlock.TYPE] = factories.TagSoundStreamBlock;
                                SWFTagFactory.sTypeToClass[factories.TagDefineBitsLossless.TYPE] = factories.TagDefineBitsLossless;
                                SWFTagFactory.sTypeToClass[factories.TagDefineBitsJPEG2.TYPE] = factories.TagDefineBitsJPEG2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineShape2.TYPE] = factories.TagDefineShape2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineButtonCxform.TYPE] = factories.TagDefineButtonCxform;
                                SWFTagFactory.sTypeToClass[factories.TagProtect.TYPE] = factories.TagProtect;
                                SWFTagFactory.sTypeToClass[factories.TagPlaceObject2.TYPE] = factories.TagPlaceObject2;
                                SWFTagFactory.sTypeToClass[factories.TagRemoveObject2.TYPE] = factories.TagRemoveObject2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineShape3.TYPE] = factories.TagDefineShape3;
                                SWFTagFactory.sTypeToClass[factories.TagDefineText2.TYPE] = factories.TagDefineText2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineButton2.TYPE] = factories.TagDefineButton2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineBitsJPEG3.TYPE] = factories.TagDefineBitsJPEG3;
                                SWFTagFactory.sTypeToClass[factories.TagDefineBitsLossless2.TYPE] = factories.TagDefineBitsLossless2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineEditText.TYPE] = factories.TagDefineEditText;
                                SWFTagFactory.sTypeToClass[factories.TagDefineSprite.TYPE] = factories.TagDefineSprite;
                                SWFTagFactory.sTypeToClass[factories.TagNameCharacter.TYPE] = factories.TagNameCharacter;
                                SWFTagFactory.sTypeToClass[factories.TagProductInfo.TYPE] = factories.TagProductInfo;
                                SWFTagFactory.sTypeToClass[factories.TagFrameLabel.TYPE] = factories.TagFrameLabel;
                                SWFTagFactory.sTypeToClass[factories.TagSoundStreamHead2.TYPE] = factories.TagSoundStreamHead2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineMorphShape.TYPE] = factories.TagDefineMorphShape;
                                SWFTagFactory.sTypeToClass[factories.TagDefineFont2.TYPE] = factories.TagDefineFont2;
                                SWFTagFactory.sTypeToClass[factories.TagExportAssets.TYPE] = factories.TagExportAssets;
                                SWFTagFactory.sTypeToClass[factories.TagImportAssets.TYPE] = factories.TagImportAssets;
                                SWFTagFactory.sTypeToClass[factories.TagEnableDebugger.TYPE] = factories.TagEnableDebugger;
                                SWFTagFactory.sTypeToClass[factories.TagDoInitAction.TYPE] = factories.TagDoInitAction;
                                SWFTagFactory.sTypeToClass[factories.TagDefineVideoStream.TYPE] = factories.TagDefineVideoStream;
                                SWFTagFactory.sTypeToClass[factories.TagVideoFrame.TYPE] = factories.TagVideoFrame;
                                SWFTagFactory.sTypeToClass[factories.TagDefineFontInfo2.TYPE] = factories.TagDefineFontInfo2;
                                SWFTagFactory.sTypeToClass[factories.TagDebugID.TYPE] = factories.TagDebugID;
                                SWFTagFactory.sTypeToClass[factories.TagEnableDebugger2.TYPE] = factories.TagEnableDebugger2;
                                SWFTagFactory.sTypeToClass[factories.TagScriptLimits.TYPE] = factories.TagScriptLimits;
                                SWFTagFactory.sTypeToClass[factories.TagSetTabIndex.TYPE] = factories.TagSetTabIndex;
                                SWFTagFactory.sTypeToClass[factories.TagFileAttributes.TYPE] = factories.TagFileAttributes;
                                SWFTagFactory.sTypeToClass[factories.TagPlaceObject3.TYPE] = factories.TagPlaceObject3;
                                SWFTagFactory.sTypeToClass[factories.TagImportAssets2.TYPE] = factories.TagImportAssets2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineFontAlignZones.TYPE] = factories.TagDefineFontAlignZones;
                                SWFTagFactory.sTypeToClass[factories.TagCSMTextSettings.TYPE] = factories.TagCSMTextSettings;
                                SWFTagFactory.sTypeToClass[factories.TagDefineFont3.TYPE] = factories.TagDefineFont3;
                                SWFTagFactory.sTypeToClass[factories.TagSymbolClass.TYPE] = factories.TagSymbolClass;
                                SWFTagFactory.sTypeToClass[factories.TagMetadata.TYPE] = factories.TagMetadata;
                                SWFTagFactory.sTypeToClass[factories.TagDefineScalingGrid.TYPE] = factories.TagDefineScalingGrid;
                                SWFTagFactory.sTypeToClass[factories.TagDefineShape4.TYPE] = factories.TagDefineShape4;
                                SWFTagFactory.sTypeToClass[factories.TagDefineMorphShape2.TYPE] = factories.TagDefineMorphShape2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineSceneAndFrameLabelData.TYPE] = factories.TagDefineSceneAndFrameLabelData;
                                SWFTagFactory.sTypeToClass[factories.TagDefineBinaryData.TYPE] = factories.TagDefineBinaryData;
                                SWFTagFactory.sTypeToClass[factories.TagDefineFontName.TYPE] = factories.TagDefineFontName;
                                SWFTagFactory.sTypeToClass[factories.TagStartSound2.TYPE] = factories.TagStartSound2;
                                SWFTagFactory.sTypeToClass[factories.TagDefineBitsJPEG4.TYPE] = factories.TagDefineBitsJPEG4;
                                SWFTagFactory.sTypeToClass[factories.TagDefineFont4.TYPE] = factories.TagDefineFont4;
                                SWFTagFactory.sTypeToClass[factories.TagEnableTelemetry.TYPE] = factories.TagEnableTelemetry;
                                SWFTagFactory.sTypeToClass[factories.TagPlaceObject4.TYPE] = factories.TagPlaceObject4;
                                SWFTagFactory.sTypeToClass[factories.TagSWFEncryptActions.TYPE] = factories.TagSWFEncryptActions;
                                SWFTagFactory.sTypeToClass[factories.TagSWFEncryptSignature.TYPE] = factories.TagSWFEncryptSignature;
                            }
                            asc.stb(SWFTagFactory, $);
                        }();
                        return SWFTagFactory;
                    }());
                    factories.SWFTagFactory = SWFTagFactory;
                })(factories = swf.factories || (swf.factories = {}));
            })(swf = format.swf || (format.swf = {}));
        })(format = __native.format || (__native.format = {}));
    })(__native = flash.__native || (flash.__native = {}));
})(flash || (flash = {}));
//# sourceMappingURL=SWFTagFactory.js.map