var flash;
(function (flash) {
    var ui;
    (function (ui) {
        ui.Capabilities = flash.system.Capabilities;
        var Keyboard = (function () {
            function Keyboard() {
            }
            Object.defineProperty(Keyboard, "capsLock", {
                get: function () {
                    return false;
                },
                enumerable: true,
                configurable: true
            });
            Object.defineProperty(Keyboard, "numLock", {
                get: function () {
                    return false;
                },
                enumerable: true,
                configurable: true
            });
            Keyboard.isAccessible = function () {
                return false;
            };
            Object.defineProperty(Keyboard, "hasVirtualKeyboard", {
                get: function () {
                    return ui.Capabilities.isMobile;
                },
                enumerable: true,
                configurable: true
            });
            Object.defineProperty(Keyboard, "physicalKeyboardType", {
                get: function () {
                    return null;
                },
                enumerable: true,
                configurable: true
            });
            Keyboard.KEYNAME_UPARROW = "Up";
            Keyboard.KEYNAME_DOWNARROW = "Down";
            Keyboard.KEYNAME_LEFTARROW = "Left";
            Keyboard.KEYNAME_RIGHTARROW = "Right";
            Keyboard.KEYNAME_F1 = "F1";
            Keyboard.KEYNAME_F2 = "F2";
            Keyboard.KEYNAME_F3 = "F3";
            Keyboard.KEYNAME_F4 = "F4";
            Keyboard.KEYNAME_F5 = "F5";
            Keyboard.KEYNAME_F6 = "F6";
            Keyboard.KEYNAME_F7 = "F7";
            Keyboard.KEYNAME_F8 = "F8";
            Keyboard.KEYNAME_F9 = "F9";
            Keyboard.KEYNAME_F10 = "F10";
            Keyboard.KEYNAME_F11 = "F11";
            Keyboard.KEYNAME_F12 = "F12";
            Keyboard.KEYNAME_F13 = "F13";
            Keyboard.KEYNAME_F14 = "F14";
            Keyboard.KEYNAME_F15 = "F15";
            Keyboard.KEYNAME_F16 = "F16";
            Keyboard.KEYNAME_F17 = "F17";
            Keyboard.KEYNAME_F18 = "F18";
            Keyboard.KEYNAME_F19 = "F19";
            Keyboard.KEYNAME_F20 = "F20";
            Keyboard.KEYNAME_F21 = "F21";
            Keyboard.KEYNAME_F22 = "F22";
            Keyboard.KEYNAME_F23 = "F23";
            Keyboard.KEYNAME_F24 = "F24";
            Keyboard.KEYNAME_F25 = "F25";
            Keyboard.KEYNAME_F26 = "F26";
            Keyboard.KEYNAME_F27 = "F27";
            Keyboard.KEYNAME_F28 = "F28";
            Keyboard.KEYNAME_F29 = "F29";
            Keyboard.KEYNAME_F30 = "F30";
            Keyboard.KEYNAME_F31 = "F31";
            Keyboard.KEYNAME_F32 = "F32";
            Keyboard.KEYNAME_F33 = "F33";
            Keyboard.KEYNAME_F34 = "F34";
            Keyboard.KEYNAME_F35 = "F35";
            Keyboard.KEYNAME_INSERT = "Insert";
            Keyboard.KEYNAME_DELETE = "Delete";
            Keyboard.KEYNAME_HOME = "Home";
            Keyboard.KEYNAME_BEGIN = "Begin";
            Keyboard.KEYNAME_END = "End";
            Keyboard.KEYNAME_PAGEUP = "PgUp";
            Keyboard.KEYNAME_PAGEDOWN = "PgDn";
            Keyboard.KEYNAME_PRINTSCREEN = "PrntScrn";
            Keyboard.KEYNAME_SCROLLLOCK = "ScrlLck";
            Keyboard.KEYNAME_PAUSE = "Pause";
            Keyboard.KEYNAME_SYSREQ = "SysReq";
            Keyboard.KEYNAME_BREAK = "Break";
            Keyboard.KEYNAME_RESET = "Reset";
            Keyboard.KEYNAME_STOP = "Stop";
            Keyboard.KEYNAME_MENU = "Menu";
            Keyboard.KEYNAME_USER = "User";
            Keyboard.KEYNAME_SYSTEM = "Sys";
            Keyboard.KEYNAME_PRINT = "Print";
            Keyboard.KEYNAME_CLEARLINE = "ClrLn";
            Keyboard.KEYNAME_CLEARDISPLAY = "ClrDsp";
            Keyboard.KEYNAME_INSERTLINE = "InsLn";
            Keyboard.KEYNAME_DELETELINE = "DelLn";
            Keyboard.KEYNAME_INSERTCHAR = "InsChr";
            Keyboard.KEYNAME_DELETECHAR = "DelChr";
            Keyboard.KEYNAME_PREV = "Prev";
            Keyboard.KEYNAME_NEXT = "Next";
            Keyboard.KEYNAME_SELECT = "Select";
            Keyboard.KEYNAME_EXECUTE = "Exec";
            Keyboard.KEYNAME_UNDO = "Undo";
            Keyboard.KEYNAME_REDO = "Redo";
            Keyboard.KEYNAME_FIND = "Find";
            Keyboard.KEYNAME_HELP = "Help";
            Keyboard.KEYNAME_MODESWITCH = "ModeSw";
            Keyboard.STRING_UPARROW = "";
            Keyboard.STRING_DOWNARROW = "";
            Keyboard.STRING_LEFTARROW = "";
            Keyboard.STRING_RIGHTARROW = "";
            Keyboard.STRING_F1 = "";
            Keyboard.STRING_F2 = "";
            Keyboard.STRING_F3 = "";
            Keyboard.STRING_F4 = "";
            Keyboard.STRING_F5 = "";
            Keyboard.STRING_F6 = "";
            Keyboard.STRING_F7 = "";
            Keyboard.STRING_F8 = "";
            Keyboard.STRING_F9 = "";
            Keyboard.STRING_F10 = "";
            Keyboard.STRING_F11 = "";
            Keyboard.STRING_F12 = "";
            Keyboard.STRING_F13 = "";
            Keyboard.STRING_F14 = "";
            Keyboard.STRING_F15 = "";
            Keyboard.STRING_F16 = "";
            Keyboard.STRING_F17 = "";
            Keyboard.STRING_F18 = "";
            Keyboard.STRING_F19 = "";
            Keyboard.STRING_F20 = "";
            Keyboard.STRING_F21 = "";
            Keyboard.STRING_F22 = "";
            Keyboard.STRING_F23 = "";
            Keyboard.STRING_F24 = "";
            Keyboard.STRING_F25 = "";
            Keyboard.STRING_F26 = "";
            Keyboard.STRING_F27 = "";
            Keyboard.STRING_F28 = "";
            Keyboard.STRING_F29 = "";
            Keyboard.STRING_F30 = "";
            Keyboard.STRING_F31 = "";
            Keyboard.STRING_F32 = "";
            Keyboard.STRING_F33 = "";
            Keyboard.STRING_F34 = "";
            Keyboard.STRING_F35 = "";
            Keyboard.STRING_INSERT = "";
            Keyboard.STRING_DELETE = "";
            Keyboard.STRING_HOME = "";
            Keyboard.STRING_BEGIN = "";
            Keyboard.STRING_END = "";
            Keyboard.STRING_PAGEUP = "";
            Keyboard.STRING_PAGEDOWN = "";
            Keyboard.STRING_PRINTSCREEN = "";
            Keyboard.STRING_SCROLLLOCK = "";
            Keyboard.STRING_PAUSE = "";
            Keyboard.STRING_SYSREQ = "";
            Keyboard.STRING_BREAK = "";
            Keyboard.STRING_RESET = "";
            Keyboard.STRING_STOP = "";
            Keyboard.STRING_MENU = "";
            Keyboard.STRING_USER = "";
            Keyboard.STRING_SYSTEM = "";
            Keyboard.STRING_PRINT = "";
            Keyboard.STRING_CLEARLINE = "";
            Keyboard.STRING_CLEARDISPLAY = "";
            Keyboard.STRING_INSERTLINE = "";
            Keyboard.STRING_DELETELINE = "";
            Keyboard.STRING_INSERTCHAR = "";
            Keyboard.STRING_DELETECHAR = "";
            Keyboard.STRING_PREV = "";
            Keyboard.STRING_NEXT = "";
            Keyboard.STRING_SELECT = "";
            Keyboard.STRING_EXECUTE = "";
            Keyboard.STRING_UNDO = "";
            Keyboard.STRING_REDO = "";
            Keyboard.STRING_FIND = "";
            Keyboard.STRING_HELP = "";
            Keyboard.STRING_MODESWITCH = "";
            Keyboard.CharCodeStrings = asc.sti(Keyboard, function () { Keyboard.CharCodeStrings = [Keyboard.KEYNAME_UPARROW, Keyboard.KEYNAME_DOWNARROW, Keyboard.KEYNAME_LEFTARROW, Keyboard.KEYNAME_RIGHTARROW, Keyboard.KEYNAME_F1, Keyboard.KEYNAME_F2, Keyboard.KEYNAME_F3, Keyboard.KEYNAME_F4, Keyboard.KEYNAME_F5, Keyboard.KEYNAME_F6, Keyboard.KEYNAME_F7, Keyboard.KEYNAME_F8, Keyboard.KEYNAME_F9, Keyboard.KEYNAME_F10, Keyboard.KEYNAME_F11, Keyboard.KEYNAME_F12, Keyboard.KEYNAME_F13, Keyboard.KEYNAME_F14, Keyboard.KEYNAME_F15, Keyboard.KEYNAME_F16, Keyboard.KEYNAME_F17, Keyboard.KEYNAME_F18, Keyboard.KEYNAME_F19, Keyboard.KEYNAME_F20, Keyboard.KEYNAME_F21, Keyboard.KEYNAME_F22, Keyboard.KEYNAME_F23, Keyboard.KEYNAME_F24, Keyboard.KEYNAME_F25, Keyboard.KEYNAME_F26, Keyboard.KEYNAME_F27, Keyboard.KEYNAME_F28, Keyboard.KEYNAME_F29, Keyboard.KEYNAME_F30, Keyboard.KEYNAME_F31, Keyboard.KEYNAME_F32, Keyboard.KEYNAME_F33, Keyboard.KEYNAME_F34, Keyboard.KEYNAME_F35, Keyboard.KEYNAME_INSERT, Keyboard.KEYNAME_DELETE, Keyboard.KEYNAME_HOME, Keyboard.KEYNAME_BEGIN, Keyboard.KEYNAME_END, Keyboard.KEYNAME_PAGEUP, Keyboard.KEYNAME_PAGEDOWN, Keyboard.KEYNAME_PRINTSCREEN, Keyboard.KEYNAME_SCROLLLOCK, Keyboard.KEYNAME_PAUSE, Keyboard.KEYNAME_SYSREQ, Keyboard.KEYNAME_BREAK, Keyboard.KEYNAME_RESET, Keyboard.KEYNAME_STOP, Keyboard.KEYNAME_MENU, Keyboard.KEYNAME_USER, Keyboard.KEYNAME_SYSTEM, Keyboard.KEYNAME_PRINT, Keyboard.KEYNAME_CLEARLINE, Keyboard.KEYNAME_CLEARDISPLAY, Keyboard.KEYNAME_INSERTLINE, Keyboard.KEYNAME_DELETELINE, Keyboard.KEYNAME_INSERTCHAR, Keyboard.KEYNAME_DELETECHAR, Keyboard.KEYNAME_PREV, Keyboard.KEYNAME_NEXT, Keyboard.KEYNAME_SELECT, Keyboard.KEYNAME_EXECUTE, Keyboard.KEYNAME_UNDO, Keyboard.KEYNAME_REDO, Keyboard.KEYNAME_FIND, Keyboard.KEYNAME_HELP, Keyboard.KEYNAME_MODESWITCH]; });
            Keyboard.NUMBER_0 = 48;
            Keyboard.NUMBER_1 = 49;
            Keyboard.NUMBER_2 = 50;
            Keyboard.NUMBER_3 = 51;
            Keyboard.NUMBER_4 = 52;
            Keyboard.NUMBER_5 = 53;
            Keyboard.NUMBER_6 = 54;
            Keyboard.NUMBER_7 = 55;
            Keyboard.NUMBER_8 = 56;
            Keyboard.NUMBER_9 = 57;
            Keyboard.A = 65;
            Keyboard.B = 66;
            Keyboard.C = 67;
            Keyboard.D = 68;
            Keyboard.E = 69;
            Keyboard.F = 70;
            Keyboard.G = 71;
            Keyboard.H = 72;
            Keyboard.I = 73;
            Keyboard.J = 74;
            Keyboard.K = 75;
            Keyboard.L = 76;
            Keyboard.M = 77;
            Keyboard.N = 78;
            Keyboard.O = 79;
            Keyboard.P = 80;
            Keyboard.Q = 81;
            Keyboard.R = 82;
            Keyboard.S = 83;
            Keyboard.T = 84;
            Keyboard.U = 85;
            Keyboard.V = 86;
            Keyboard.W = 87;
            Keyboard.X = 88;
            Keyboard.Y = 89;
            Keyboard.Z = 90;
            Keyboard.SEMICOLON = 186;
            Keyboard.EQUAL = 187;
            Keyboard.COMMA = 188;
            Keyboard.MINUS = 189;
            Keyboard.PERIOD = 190;
            Keyboard.SLASH = 191;
            Keyboard.BACKQUOTE = 192;
            Keyboard.LEFTBRACKET = 219;
            Keyboard.BACKSLASH = 220;
            Keyboard.RIGHTBRACKET = 221;
            Keyboard.QUOTE = 222;
            Keyboard.ALTERNATE = 18;
            Keyboard.BACKSPACE = 8;
            Keyboard.CAPS_LOCK = 20;
            Keyboard.COMMAND = 15;
            Keyboard.CONTROL = 17;
            Keyboard.DELETE = 46;
            Keyboard.DOWN = 40;
            Keyboard.END = 35;
            Keyboard.ENTER = 13;
            Keyboard.ESCAPE = 27;
            Keyboard.F1 = 112;
            Keyboard.F2 = 113;
            Keyboard.F3 = 114;
            Keyboard.F4 = 115;
            Keyboard.F5 = 116;
            Keyboard.F6 = 117;
            Keyboard.F7 = 118;
            Keyboard.F8 = 119;
            Keyboard.F9 = 120;
            Keyboard.F10 = 121;
            Keyboard.F11 = 122;
            Keyboard.F12 = 123;
            Keyboard.F13 = 124;
            Keyboard.F14 = 125;
            Keyboard.F15 = 126;
            Keyboard.HOME = 36;
            Keyboard.INSERT = 45;
            Keyboard.LEFT = 37;
            Keyboard.NUMPAD = 21;
            Keyboard.NUMPAD_0 = 96;
            Keyboard.NUMPAD_1 = 97;
            Keyboard.NUMPAD_2 = 98;
            Keyboard.NUMPAD_3 = 99;
            Keyboard.NUMPAD_4 = 100;
            Keyboard.NUMPAD_5 = 101;
            Keyboard.NUMPAD_6 = 102;
            Keyboard.NUMPAD_7 = 103;
            Keyboard.NUMPAD_8 = 104;
            Keyboard.NUMPAD_9 = 105;
            Keyboard.NUMPAD_ADD = 107;
            Keyboard.NUMPAD_DECIMAL = 110;
            Keyboard.NUMPAD_DIVIDE = 111;
            Keyboard.NUMPAD_ENTER = 108;
            Keyboard.NUMPAD_MULTIPLY = 106;
            Keyboard.NUMPAD_SUBTRACT = 109;
            Keyboard.PAGE_DOWN = 34;
            Keyboard.PAGE_UP = 33;
            Keyboard.RIGHT = 39;
            Keyboard.SHIFT = 16;
            Keyboard.SPACE = 32;
            Keyboard.TAB = 9;
            Keyboard.UP = 38;
            Keyboard.RED = 16777216;
            Keyboard.GREEN = 16777217;
            Keyboard.YELLOW = 16777218;
            Keyboard.BLUE = 16777219;
            Keyboard.CHANNEL_UP = 16777220;
            Keyboard.CHANNEL_DOWN = 16777221;
            Keyboard.RECORD = 16777222;
            Keyboard.PLAY = 16777223;
            Keyboard.PAUSE = 16777224;
            Keyboard.STOP = 16777225;
            Keyboard.FAST_FORWARD = 16777226;
            Keyboard.REWIND = 16777227;
            Keyboard.SKIP_FORWARD = 16777228;
            Keyboard.SKIP_BACKWARD = 16777229;
            Keyboard.NEXT = 16777230;
            Keyboard.PREVIOUS = 16777231;
            Keyboard.LIVE = 16777232;
            Keyboard.LAST = 16777233;
            Keyboard.MENU = 16777234;
            Keyboard.INFO = 16777235;
            Keyboard.GUIDE = 16777236;
            Keyboard.EXIT = 16777237;
            Keyboard.BACK = 16777238;
            Keyboard.AUDIO = 16777239;
            Keyboard.SUBTITLE = 16777240;
            Keyboard.DVR = 16777241;
            Keyboard.VOD = 16777242;
            Keyboard.INPUT = 16777243;
            Keyboard.SETUP = 16777244;
            Keyboard.HELP = 16777245;
            Keyboard.MASTER_SHELL = 16777246;
            Keyboard.SEARCH = 16777247;
            return Keyboard;
        }());
        ui.Keyboard = Keyboard;
    })(ui = flash.ui || (flash.ui = {}));
})(flash || (flash = {}));
//# sourceMappingURL=Keyboard.js.map